### ISSUE TITLE
v0.25.2のUpdate時にエラーが発生する

### ISSUE THREAD

**Issue by ayuki-joto** [codeforjapan/decidim-cfj#373]
## 対象ドメイン/ The domain
- なし

## 起こっている問題 / The Problem
- #372　のブランチで`bin/rails decidim:upgrade`を実行するとエラーが以下のエラーが発生する
```
NoMethodError: undefined method `set_variants' for Decidim::AvatarUploader:Class
NoMethodError: undefined method `set_variants' for Decidim::AvatarUploader:Class
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/decidim-core-0.25.2/app/uploaders/decidim/avatar_uploader.rb:6:in `<class:AvatarUploader>'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/decidim-core-0.25.2/app/uploaders/decidim/avatar_uploader.rb:5:in `<module:Decidim>'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/decidim-core-0.25.2/app/uploaders/decidim/avatar_uploader.rb:3:in `<main>'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:515:in `block in load_file'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:706:in `new_constants_in'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:514:in `load_file'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:411:in `block in require_or_load'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:40:in `block in load_interlock'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies/interlock.rb:13:in `loading'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:40:in `load_interlock'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:394:in `require_or_load'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:549:in `load_missing_constant'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:214:in `const_missing'
/decidim-cfj/app/models/decidim/user_base_entity.rb:24:in `<class:UserBaseEntity>'
/decidim-cfj/app/models/decidim/user_base_entity.rb:7:in `<module:Decidim>'
/decidim-cfj/app/models/decidim/user_base_entity.rb:3:in `<main>'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:515:in `block in load_file'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:706:in `new_constants_in'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:514:in `load_file'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:411:in `block in require_or_load'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:40:in `block in load_interlock'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies/interlock.rb:13:in `loading'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:40:in `load_interlock'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:394:in `require_or_load'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:549:in `load_missing_constant'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:214:in `const_missing'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/decidim-core-0.25.2/app/models/decidim/user.rb:9:in `<module:Decidim>'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/decidim-core-0.25.2/app/models/decidim/user.rb:7:in `<main>'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:515:in `block in load_file'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:706:in `new_constants_in'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:514:in `load_file'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:411:in `block in require_or_load'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:40:in `block in load_interlock'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies/interlock.rb:13:in `loading'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:40:in `load_interlock'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:394:in `require_or_load'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:549:in `load_missing_constant'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:214:in `const_missing'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/decidim-decidim_awesome-0.8.2/lib/decidim/decidim_awesome/engine.rb:31:in `block in <class:Engine>'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/callbacks.rb:428:in `instance_exec'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/callbacks.rb:605:in `block (2 levels) in default_terminator'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/callbacks.rb:604:in `catch'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/callbacks.rb:604:in `block in default_terminator'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/callbacks.rb:201:in `block in halting'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/callbacks.rb:513:in `each'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/callbacks.rb:513:in `invoke_before'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/callbacks.rb:134:in `run_callbacks'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/reloader.rb:88:in `prepare!'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.7/lib/rails/application/finisher.rb:113:in `block in <module:Finisher>'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.7/lib/rails/initializable.rb:32:in `instance_exec'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.7/lib/rails/initializable.rb:32:in `run'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.7/lib/rails/initializable.rb:61:in `block in run_initializers'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.7/lib/rails/initializable.rb:60:in `run_initializers'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.7/lib/rails/application.rb:363:in `initialize!'
/decidim-cfj/config/environment.rb:7:in `<main>'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:324:in `block in require'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:291:in `load_dependency'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4.7/lib/active_support/dependencies.rb:324:in `require'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.7/lib/rails/application.rb:339:in `require_environment!'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.7/lib/rails/application.rb:523:in `block in run_tasks_blocks'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.7/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.7/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.7/lib/rails/command.rb:48:in `invoke'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/railties-6.0.4.7/lib/rails/commands.rb:18:in `<main>'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/decidim-cfj/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:6:in `<main>'
Tasks: TOP => decidim:upgrade => railties:install:migrations => db:load_config => environment
(See full trace by running task with --trace)
```
## 期待する見せ方・挙動 / Expected Behavior
- エラーがなく実行できる

## 起こっている問題の再現手段 / Steps to Reproduce
1. bin/rails decidim:upgrade　

## 動作環境・ブラウザ / Environment
- macOS /

**Comment by takahashim** [comment]
これは app/uploaders/decidim/application_uploader.rb が更新されてないからですね…。
先に #323 に対応した方が良さそうです。

**Comment by takahashim** [comment]
ああ、でも結局`url`を上書きしてるからダメなんですね…。
とはいえファイルまるごと上書きし続けるのは大変なので、prependするように変えるべき？

**Comment by ayuki-joto** [comment]
あー、クラウドフロントから送るようにしたやつの対応ですね。。。
一度上げてみて試しましょうか。。。

**Comment by ayuki-joto** [comment]
一旦最新のものをマージしてコマンドの実行はできたのでcloseします！
