### ISSUE TITLE
docker-compose.yamlでポスグレのパスワード環境変数が差し込めるようになっていない

### ISSUE THREAD

**Issue by komtaki** [codeforjapan/decidim-cfj#9]
## 対象ドメイン/ The domain
- 開発環境構築時

## 起こっている問題 / The Problem
- docker-compose.yamlにポスグレのパスワード環境変数が差し込めるようになっていないので、コンテナの起動に失敗する

## スクリーンショット / Screenshot

![キャプチャ](https://user-images.githubusercontent.com/39375566/96448366-3e7c1380-124e-11eb-9a78-7a39456e8d21.JPG)

```
app_1  | => Booting Puma
app_1  | => Rails 5.2.4.4 application starting in development
app_1  | => Run `rails server -h` for more startup options
app_1  | Puma starting in single mode...
app_1  | * Version 5.0.2 (ruby 2.6.6-p146), codename: Spoony Bard
app_1  | * Min threads: 5, max threads: 5
app_1  | * Environment: development
app_1  | * Listening on http://0.0.0.0:3000
app_1  | Use Ctrl-C to stop
app_1  | Started GET "/system/admins/sign_in" for 192.168.32.1 at 2020-10-19 12:00:44 +0000
app_1  | Cannot render console from 192.168.32.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
app_1  |   
app_1  | PG::ConnectionBad (fe_sendauth: no password supplied
app_1  | ):
app_1  |   
app_1  | pg (1.1.4) lib/pg.rb:56:in `initialize'
app_1  | pg (1.1.4) lib/pg.rb:56:in `new'
app_1  | pg (1.1.4) lib/pg.rb:56:in `connect'
app_1  | activerecord (5.2.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
app_1  | activerecord (5.2.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
app_1  | activerecord (5.2.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
app_1  | activerecord (5.2.4.4) lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
```

## 期待する見せ方・挙動 / Expected Behavior
- アプリの画面が見える

## 起こっている問題の再現手段 / Steps to Reproduce
1. docker-compose up

## 動作環境・ブラウザ / Environment
- Windows

**Comment by halsk** [comment]
@komtaki これもクローズしても良いでしょうか。

**Comment by komtaki** [comment]
マージありがとうございます。closeで。
